const MODAL_KEYS = {
  TLS: "TLS",
  KEY: "KEY",
  RAS: "RAS",
  RADIO: "RADIO",
  RADIO_TYPES: "RADIO_TYPES",
  ORGANISM: "ORGANISM",
  FIRMWARE: "FIRMWARE",
  CHANNEL: "CHANNEL",
  RADIO_CHECK: "RADIO_CHECK",
  RADIO_GIVING: "RADIO_GIVING",
};

export default MODAL_KEYS;
